"""Export the Gate-2 flood pilot scene as RaySAR-ready POV-Ray scenes.

RaySAR conventions (see /Users/romitbasak/Projects/RaySAR/ASSESSMENT.md and
POV-Ray_Testfile/Box.pov): ORTHOGRAPHIC camera is the SAR sensor (|right| =
azimuth extent, |up| = elevation extent, view direction = range), one
`parallel` light co-located with the camera (monostatic), and the BLUE
channel of pigment/reflection carries radar reflectivity. `ambient 0`
everywhere or POV's default ambient injects fake signal.

Frame: sarsim is right-handed Z-up; POV is left-handed Y-up. Map
(x, y, z)_sarsim -> (x, z, y)_pov. Radar sits on the sarsim -y side
(POV -z) at 37.5 deg incidence from vertical, matching Gate 2.

Material map: sarsim (rho_d, rho_s, phong_p) -> finish { diffuse rho_d
reflection {rgb <0,0,rho_s>} specular rho_s roughness 1/phong_p } with
pure-blue pigment. The `specular` highlight is load-bearing for double
bounce: RaySAR's dihedral return is the highlight firing at the SECOND
surface when the reflected view ray aligns with the light's mirror
direction (cf. Box.pov's smooth objects); reflection{} alone leaves the
second leg lit only by its diffuse term, which near-kills water.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from sarsim.scenes import flood_pilot
from sarsim.tracer_ref import TriScene

MAT_FINISH = {  # name -> (rho_d, rho_s, phong_p), mirrors scenes.flood_pilot
    'soil':  (0.15, 0.05, 10.0),
    'wall':  (0.10, 0.50, 60.0),
    'roof':  (0.20, 0.02, 5.0),
    'water': (0.01, 0.70, 400.0),
}
_ORDER = list(MAT_FINISH)

INCIDENCE_DEG = 37.5
EXTENT = 50.0          # |right| = |up|: azimuth/elevation window (m)
STANDOFF = 200.0       # camera distance; orthographic, so arbitrary


def pov_scene(water: bool) -> str:
    scene: TriScene = flood_pilot(water=water)
    inc = np.deg2rad(INCIDENCE_DEG)
    # POV camera position: -z side, elevated (y up), looking at origin
    loc = STANDOFF * np.array([0.0, np.cos(inc), -np.sin(inc)])

    L = [
        '// generated by sarsim/scripts/export_pilot_pov.py — do not edit',
        f'// flood_pilot(water={water}), incidence {INCIDENCE_DEG} deg,'
        f' azimuth/elevation window {EXTENT} m',
        'global_settings { SAR_Output_Data 1 SAR_Intersection 0'
        ' max_trace_level 3 }',
        '',
        'camera {',
        '  orthographic',
        f'  location <{loc[0]:.4f}, {loc[1]:.4f}, {loc[2]:.4f}>',
        '  look_at  <0, 0, 0>',
        f'  right {EXTENT}*x',
        f'  up {EXTENT}*y',
        '}',
        '',
        'light_source {',
        '  0*x',
        '  color rgb <1,1,1>',
        '  parallel',
        f'  translate <{loc[0]:.4f}, {loc[1]:.4f}, {loc[2]:.4f}>',
        '  point_at <0, 0, 0>',
        '}',
        '',
    ]
    for name, (rho_d, rho_s, phong_p) in MAT_FINISH.items():
        L += [f'#declare T_{name} = texture {{',
              '  pigment { color rgb <0,0,1> }',
              f'  finish {{ ambient 0 diffuse {rho_d}'
              f' reflection {{ rgb <0,0,{rho_s}> }}'
              f' specular {rho_s} roughness {1.0 / phong_p:.5f} }}',
              '}']
    L.append('')
    for mi, name in enumerate(_ORDER):
        sel = np.flatnonzero(scene.mat_idx == mi)
        if not len(sel):
            continue
        L.append(f'mesh {{ // {name}: {len(sel)} tris')
        for ti in sel:
            vs = []
            for v in (scene.v0[ti], scene.v1[ti], scene.v2[ti]):
                vs.append(f'<{v[0]:.4f}, {v[2]:.4f}, {v[1]:.4f}>')  # z-up->y-up
            L.append(f'  triangle {{ {vs[0]}, {vs[1]}, {vs[2]} }}')
        L += [f'  texture {{ T_{name} }}', '}', '']
    return '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('out_dir', help='directory for pilot_{dry,wet}.pov')
    args = ap.parse_args()
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for water, name in [(False, 'pilot_dry'), (True, 'pilot_wet')]:
        p = out / f'{name}.pov'
        p.write_text(pov_scene(water))
        print(p)


if __name__ == '__main__':
    main()
